-- AlterTable
ALTER TABLE "UserProgress" ADD COLUMN     "clearWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cloudyWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedEpicItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedLegendaryItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedNormalItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedRareItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "collectedUncommonItemTypesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "consecutiveWalkDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastWalkDate" TIMESTAMP(3),
ADD COLUMN     "nightWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rainyWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "snowyWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sunnyWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "thunderstormWalkCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "windyWalkCount" INTEGER NOT NULL DEFAULT 0;
