// src/app/layout.tsx
import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";
// import SessionProviderWrapper from './components/SessionProviderWrapper'; // ★ 削除

const rounded_mplus = M_PLUS_Rounded_1c({
    subsets: ["latin"],
    weight: ["400", "500", "800"],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={rounded_mplus.className}>
                {/* ★ SessionProviderWrapper のラップを解除 */}
                <div className="hidden bg-sunny bg-cloudy bg-rainy bg-snowy bg-night bg-green-100"></div>
                {children}
            </body>
        </html>
    );
}